### PR TITLE
Add Docker, configurable CRS, HTTP endpoint dataset refresh, new servlets

### PR DESCRIPTION
**Pull request by yosoyjay**
Updates:
- Add Docker support and Travis CI
- Add support for configurable advertised CRS codes in config.xml
- Add ability to refresh dataset via HTTP endpoint
- Add servlet to handle API requests about datasets
- Add servlet that returns Ehcache stats

Note:  Dockerfile will be updated to point to Reading-eScience-Centre/EDAL in future pull request.

### CODE REVIEW

**Comment by guygriffiths** [comment]
Looks good, thanks.

**Comment by yosoyjay** [comment]
Thanks Guy, I'll take a look at your changes and take better note of the
style conventions.  And, I'll go through the servlets and add Javadocs as
you suggest.

**Comment by guygriffiths** [comment]
Is there a particular reason that Docker:
a) Builds everything from scratch (rather than just downloading the latest release), and
b) Uses the axiom-data-science fork, rather than the main repo?

**Comment by yosoyjay** [comment]
Yeah, it just has to do with development issues. 

a) It's useful to have ncWMS compile to integrate changes into CI pipelines.  The build could be sped up substantially by removing the build of edal-java.  It was included because the ncWMS build would fail if edal-java wasn't installed in the Docker build.  In fact, I just tried building it locally (outside of Docker) after clearing the local Maven cache and I get a build failure.

```[ERROR] Failed to execute goal on project ncWMS: Could not resolve dependencies for project uk.ac.rdg.resc:ncWMS:war:2.2.8-SNAPSHOT: The following artifacts could not be resolved: uk.ac.rdg.resc:edal-common:jar:1.2.8-SNAPSHOT, uk.ac.rdg.resc:edal-graphics:jar:1.2.8-SNAPSHOT, uk.ac.rdg.resc:edal-godiva:jar:1.2.8-SNAPSHOT, uk.ac.rdg.resc:edal-cdm:jar:1.2.8-SNAPSHOT, uk.ac.rdg.resc:edal-xml-catalogue:jar:1.2.8-SNAPSHOT, uk.ac.rdg.resc:edal-wms:jar:1.2.8-SNAPSHOT: Could not find artifact uk.ac.rdg.resc:edal-common:jar:1.2.8-SNAPSHOT -> [Help 1]```

b) There were features in edal-java that were only available in the axiom-data-science fork that were required for compiling.  Recent pull requests have resolved that issue, so that can be changed.  Or, if the build works, it could just be removed.

**Comment by guygriffiths** [comment]
a) Ah OK, I hadn't spotted that it was building the EDAL libraries, rather than ncWMS, that makes sense.
b) OK, I'll change that before the next release

**Comment by acrosby** [comment]
Is this in the current release, specifically the http endpoint for dataset refreshes?

Thanks!

**Comment by guygriffiths** [comment]
@acrosby - Yep, should all be in the current release

**Pull request merged**
