### PR TITLE
Add default dynamic cache

### PR DESCRIPTION
**Pull request by yosoyjay**
Fix for when users do not supply ehcache.xml file to define dynamicDatasetCache.  Uses same values previously defined.

### CODE REVIEW

**Comment by guygriffiths** [comment]
The code looks fine, but it adds a few compiler warnings - could you remove the unused imports before I merge this?

**Comment by yosoyjay** [comment]
What is the specific warnings?  I'm seeing the same warnings that I see in the develop branch using JDK 1.8.0_51.

Are these the warnings?

```
Running uk.ac.rdg.resc.edal.ncwms.config.NcwmsConfigTest
log4j:WARN File option not set for appender [file].
log4j:WARN Are you using FileAppender instead of ConsoleAppender?
...
```

and

```
[INFO] --- exec-maven-plugin:1.5.0:java (generate-palettes) @ ncWMS ---
SLF4J: The requested version 1.6.99 by your slf4j binding is not compatible with [1.5.5, 1.5.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
log4j:WARN File option not set for appender [file].
log4j:WARN Are you using FileAppender instead of ConsoleAppender?
```

**Comment by guygriffiths** [comment]
No, it's just compiler warnings from some imports at the top of NcwmsCatalogue which are never used.  On Eclipse, I just do Ctrl+Shift+O to organise imports and remove any unused ones.  I expect there's something similar in most IDEs

**Comment by yosoyjay** [comment]
Ah, gotcha.  All fixed up.

**Comment by guygriffiths** [comment]
Great, thanks

**Pull request merged**
